-- Startup
function InitGame(levelTime, randomSeed, restart)
	game.Print("Lua Level Init...");
	game.Print("-map_restart ...");
		game.Print("--workaround-setup ...");
			ent = entity.Spawn();
			ent:SetKeyValue("classname", "target_levelchange");
			ent:SetKeyValue("targetname", "map_restart");
			ent:SetKeyValue("target", "borg4");
			entity.CallSpawn(ent);
		game.Print("--trigger-setup ...");
		if restart == 1 then
			game.ClientPrint(-1, "Please don't use map_restart, use map or devmap instead.");
			game.Print("Please don't use map_restart, use map or devmap instead.");
			ent = entity.Find("map_restart")
			entity.Use(ent)
		end
	game.Print("-Updating and fixing Forcefields and Plasmafilters...");
		game.Print("--Forcefield Section 1");
			ent = entity.Spawn();
			ent:SetKeyValue("classname", "misc_model_breakable");
			ent:SetKeyValue("target", "forcefield2");
			ent:SetKeyValue("health", "1");  
			ent:SetKeyValue("spawnflags", "1"); 
			ent:SetKeyValue("splashDamage", "75");  
			ent:SetKeyValue("splashRadius", "75");
			ent:SetKeyValue("material", "1");  
			ent:SetKeyValue("model", "models/mapobjects/borg/disnode.md3"); 
			mover.SetPosition(ent, -1268, 53, 36);
			mover.SetAngles(ent, 0, 270, 0);
			entity.CallSpawn(ent); 
			ent = entity.FindBModel(56);
			ent:SetKeyValue("classname", "func_forcefield");      
			entity.CallSpawn(ent); 
  		game.Print("--Plasmafilter Room 1");
			ent = entity.Spawn();
			ent:SetKeyValue("classname", "misc_model_breakable");
			ent:SetKeyValue("target", "t49");
			ent:SetKeyValue("health", "1");
			ent:SetKeyValue("spawnflags", "9");
			ent:SetKeyValue("splashDamage", "250");
			ent:SetKeyValue("splashRadius", "150");
			ent:SetKeyValue("material", "1");
			ent:SetKeyValue("model", "models/mapobjects/borg/tank.md3");
			mover.SetPosition(ent, -68, -432, 94);
			mover.SetAngles(ent, 0, 180, 0);
			entity.CallSpawn(ent);
			ent = entity.FindBModel(8);
			ent:SetKeyValue("classname", "func_breakable");
			ent:SetKeyValue("spawnflags", "1");
			ent:SetKeyValue("material", "1");
			entity.CallSpawn(ent);
		game.Print("--Plasmafilter Corridor");
			ent = entity.Spawn();
			ent:SetKeyValue("classname", "misc_model_breakable");
			ent:SetKeyValue("target", "t50");
			ent:SetKeyValue("health", "1");
			ent:SetKeyValue("spawnflags", "9");
			ent:SetKeyValue("splashDamage", "250");
			ent:SetKeyValue("splashRadius", "150");
			ent:SetKeyValue("material", "1");
			ent:SetKeyValue("model", "models/mapobjects/borg/tank.md3");
			mover.SetPosition(ent, -1340, 1056, -636);
			mover.SetAngles(ent, 0, 180, 0);
			entity.CallSpawn(ent);
			ent = entity.FindBModel(7);
			ent:SetKeyValue("classname", "func_breakable");
			ent:SetKeyValue("spawnflags", "1");
			ent:SetKeyValue("material", "1");
			entity.CallSpawn(ent);
		game.Print("--Forcefield last Room");
			ent = entity.Spawn();
			ent:SetKeyValue("classname", "misc_model_breakable");
			ent:SetKeyValue("target", "forcefield1");
			ent:SetKeyValue("health", "1");
			ent:SetKeyValue("spawnflags", "1");
			ent:SetKeyValue("splashDamage", "75");  
			ent:SetKeyValue("splashRadius", "75");
			ent:SetKeyValue("material", "1");    
			ent:SetKeyValue("model", "models/mapobjects/borg/disnode.md3"); 
			mover.SetPosition(ent, -1616, 1909, -616);
			mover.SetAngles(ent, 0, 270, 0);
			entity.CallSpawn(ent); 
			ent = entity.FindBModel(6);
			ent:SetKeyValue("classname", "func_forcefield");      
			entity.CallSpawn(ent);  
	game.Print("-Some Decorative Work and fixes...");
		ent = entity.Find("seven_basescreen");
		ent:SetKeyValue("target", "seven_harvscreen");
		ent:SetKeyValue("luaUse", "sound7base");
		entity.CallSpawn(ent);
		ent = entity.Find("seven_harvscreen");
		ent:SetKeyValue("target", "seven_forgescreen");
		ent:SetKeyValue("luaUse", "sound7harv");
		entity.CallSpawn(ent);
		ent = entity.Find("seven_forgescreen");
		ent:SetKeyValue("target", "seven_basescreen");
		ent:SetKeyValue("luaUse", "sound7forge");
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin.md3");
		mover.SetPosition(ent, 671, -262, 53);
		mover.SetAngles(ent, 0, 90, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin.md3");
		mover.SetPosition(ent, 993, -318, 53);
		mover.SetAngles(ent, 0, 90, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin.md3");
		mover.SetPosition(ent, 1414, -368, 53);
		mover.SetAngles(ent, 0, 180, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin2.md3"); 
		mover.SetPosition(ent, 994, -142, 53);
		mover.SetAngles(ent, 0, 270, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin.md3");
		mover.SetPosition(ent, 469, 47, 40);
		mover.SetAngles(ent, 0, 270, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin2.md3");
		mover.SetPosition(ent, 13, -465, 48);
		mover.SetAngles(ent, 0, 270, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin2.md3");
		mover.SetPosition(ent, -528, 32, 48);
		mover.SetAngles(ent, 0, 180, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin.md3");
		mover.SetPosition(ent, -64, 328, 48);
		mover.SetAngles(ent, 0, 180, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin.md3");
		mover.SetPosition(ent, -971, -295, 48);
		mover.SetAngles(ent, 0, 90, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin2.md3");
		mover.SetPosition(ent, -1505, -249, 32);
		mover.SetAngles(ent, 0, 180, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin.md3");
		mover.SetPosition(ent, -1311, -247, 32);
		mover.SetAngles(ent, 0, 0, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin.md3");
		mover.SetPosition(ent, -1807, 521, -352);
		mover.SetAngles(ent, 0, 0, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin.md3");
		mover.SetPosition(ent, -2089, 1401, -624);
		mover.SetAngles(ent, 0, 90, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin2.md3");
		mover.SetPosition(ent, -1713, 1972, -624);
		mover.SetAngles(ent, 0, 180, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "misc_model_breakable");
		ent:SetKeyValue("spawnflags", "17");
		ent:SetKeyValue("model", "models/mapobjects/borg/plugin.md3");
		mover.SetPosition(ent, -2255, 1973, -624);
		mover.SetAngles(ent, 0, 0, 0);
		entity.CallSpawn(ent);
	game.Print("-Transfer...");
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "target_levelchange");
		ent:SetKeyValue("targetname", "elone");
		ent:SetKeyValue("target", "borg5");
		ent:SetKeyValue("wait", "6");
		mover.SetPosition(ent, 0, 0, 0);
		entity.CallSpawn(ent);
		ent = entity.FindBModel(63);
		ent:SetKeyValue("classname", "func_usable");
		ent:SetKeyValue("spawnflags", "8");
		ent:SetKeyValue("wait", "1");
		ent:SetKeyValue("target", "elone");
		ent:SetKeyValue("luaUse", "sound63");
		entity.CallSpawn(ent);
		ent = entity.FindBModel(24);
		ent:SetKeyValue("classname", "func_door");
		ent:SetKeyValue("wait", "-1");
		ent:SetKeyValue("angle", "-2");
		ent:SetKeyValue("count", "-460");
		ent:SetKeyValue("speed", "75");
		entity.CallSpawn(ent);
	game.Print("-Lift A fix...");
		ent = entity.FindBModel(51);
		ent:SetKeyValue("classname", "func_usable");
		ent:SetKeyValue("spawnflags", "8");
		ent:SetKeyValue("wait", "1");    
		ent:SetKeyValue("target", "t7");
		ent:SetKeyValue("luaUse", "sound51");
		entity.CallSpawn(ent);  
		ent = entity.FindBModel(52);
		ent:SetKeyValue("classname", "func_usable");
		ent:SetKeyValue("spawnflags", "8");
		ent:SetKeyValue("wait", "1");    
		ent:SetKeyValue("target", "t7");
		ent:SetKeyValue("luaUse", "sound52");
		entity.CallSpawn(ent); 
		ent = entity.FindBModel(23);
		ent:SetKeyValue("wait", "-1");
		ent:SetKeyValue("angle", "-2");  
		ent:SetKeyValue("count", "16");
		entity.CallSpawn(ent); 
	game.Print("-Lift B fix...");
		ent = entity.FindBModel(54);
		ent:SetKeyValue("classname", "func_usable");
		ent:SetKeyValue("spawnflags", "8");
		ent:SetKeyValue("wait", "1");    
		ent:SetKeyValue("target", "t8");
		ent:SetKeyValue("luaUse", "sound54");
		entity.CallSpawn(ent);  
		ent = entity.FindBModel(53);
		ent:SetKeyValue("classname", "func_usable");
		ent:SetKeyValue("spawnflags", "8");
		ent:SetKeyValue("wait", "1");    
		ent:SetKeyValue("target", "t8");
		ent:SetKeyValue("luaUse", "sound53");
		entity.CallSpawn(ent);    
		ent = entity.FindBModel(22);
		ent:SetKeyValue("wait", "-1");
		ent:SetKeyValue("angle", "-2");   
		ent:SetKeyValue("count", "16");
		entity.CallSpawn(ent); 
	game.Print("-Setting up spawnpoints...");
		entity.RemoveSpawns();
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "info_player_deathmatch");
		mover.SetPosition(ent, 456, -152, 16);
		mover.SetAngles(ent, 0, 90, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "info_player_deathmatch");
		mover.SetPosition(ent, 424, -120, 16);
		mover.SetAngles(ent, 0, 90, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "info_player_deathmatch");
		mover.SetPosition(ent, 424, -184, 16);
		mover.SetAngles(ent, 0, 90, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "info_player_deathmatch");
		mover.SetPosition(ent, 488, -120, 16);
		mover.SetAngles(ent, 0, 90, 0);
		entity.CallSpawn(ent);
		ent = entity.Spawn();
		ent:SetKeyValue("classname", "info_player_deathmatch");
		mover.SetPosition(ent, 488, -184, 16);
		mover.SetAngles(ent, 0, 90, 0);
		entity.CallSpawn(ent);
	game.Print("-Breakable-Mod...");
		game.Print("--misc_model_breakable...");
			game.Print("---checking for local or dedicated...");
				if not entity.FindNumber(236) == nil then
				ent = entity.FindNumber(236);
				test = ent.GetClassname(ent);
				if test == "misc_model_breakable" then
			game.Print("----dedicated...");
				ent = entity.FindNumber(192);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(193);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(194);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(195);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(196);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(200);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(201);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(202);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(203);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(229);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(231);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(232);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(233);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(234);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(236);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				else
			game.Print("----local...");
				ent = entity.FindNumber(190);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(191);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(192);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(193);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(194);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(198);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(199);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(200);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(201);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(215);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(217);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(218);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(219);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(220);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(222);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				end
				else
			game.Print("----local...");
				ent = entity.FindNumber(190);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(191);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(192);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(193);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(194);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(198);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(199);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(200);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(201);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(215);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(217);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(218);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(219);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(220);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				ent = entity.FindNumber(222);
				ent:SetKeyValue("material", "2");
				ent:SetKeyValue("splashDamage", "75");
				ent:SetKeyValue("splashRadius", "75");
				entity.CallSpawn(ent);
				end
game.Print("...Done"); 	
end 

--Sounds

function sound51(ent, other, activator)
    sound.PlaySound(entity.FindBModel(51), "sound/movers/switches/borglcarswitch.mp3", 0);
end

function sound52(ent, other, activator)
    sound.PlaySound(entity.FindBModel(52), "sound/movers/switches/borglcarswitch.mp3", 0);
end

function sound53(ent, other, activator)
    sound.PlaySound(entity.FindBModel(53), "sound/movers/switches/borglcarswitch.mp3", 0);
end

function sound54(ent, other, activator)
    sound.PlaySound(entity.FindBModel(54), "sound/movers/switches/borglcarswitch.mp3", 0);
end 

function sound63(ent, other, activator)
    sound.PlaySound(entity.FindBModel(63), "sound/movers/switches/borglcarswitch.mp3", 0);
end 

function sound7base(ent, other, activator)
    sound.PlaySound(entity.Find("seven_basescreen"), "sound/movers/switches/borglcarswitch.mp3", 0);
end

function sound7harv(ent, other, activator)
    sound.PlaySound(entity.Find("seven_harvscreen"), "sound/movers/switches/borglcarswitch.mp3", 0);
end 

function sound7forge(ent, other, activator)
    sound.PlaySound(entity.Find("seven_forgescreen"), "sound/movers/switches/borglcarswitch.mp3", 0);
end    